[colors]
background       = '#f6f2ee'
black            = '#352c24'
blue             = '#2848a9'
cursor           = '#3d2b5a'
cyan             = '#287980'
foreground       = '#3d2b5a'
green            = '#396847'
magenta          = '#6e33ce'
red              = '#a5222f'
tabs             = '#352c24'
tabs-active      = '#534c45'
white            = '#f2e9e1'
yellow           = '#ac5402'
dim-black        = '#2d251f'
dim-blue         = '#223d90'
dim-cyan         = '#22676d'
dim-foreground   = '#302b5d'
dim-green        = '#30583c'
dim-magenta      = '#5e2baf'
dim-red          = '#8c1d28'
dim-white        = '#cec6bf'
dim-yellow       = '#924702'
light-black      = '#534c45'
light-blue       = '#4863b6'
light-cyan       = '#488d93'
light-foreground = '#643f61'
light-green      = '#577f63'
light-magenta    = '#8452d5'
light-red        = '#b3434e'
light-white      = '#f4ece6'
light-yellow     = '#b86e28'

