# Nightfox Alacritty Colors
## name: nightfox
## upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/nightfox/alacritty.toml

[colors]
background       = '#192330'
black            = '#393b44'
blue             = '#719cd6'
cursor           = '#cdcecf'
cyan             = '#63cdcf'
foreground       = '#cdcecf'
green            = '#81b29a'
magenta          = '#9d79d6'
red              = '#c94f6d'
tabs             = '#393b44'
tabs-active      = '#575860'
white            = '#dfdfe0'
yellow           = '#dbc074'
dim-black        = '#30323a'
dim-blue         = '#6085b6'
dim-cyan         = '#54aeb0'
dim-foreground   = '#aeafb0'
dim-green        = '#6e9783'
dim-magenta      = '#8567b6'
dim-red          = '#ab435d'
dim-white        = '#bebebe'
dim-yellow       = '#baa363'
light-black      = '#575860'
light-blue       = '#86abdc'
light-cyan       = '#7ad5d6'
light-foreground = '#d6d6d7'
light-green      = '#8ebaa4'
light-magenta    = '#baa1e2'
light-red        = '#d16983'
light-white      = '#e4e4e5'
light-yellow     = '#e0c989'
