[colors]
background       = '#2e3440'
black            = '#3b4252'
blue             = '#81a1c1'
cursor           = '#cdcecf'
cyan             = '#88c0d0'
foreground       = '#cdcecf'
green            = '#a3be8c'
magenta          = '#b48ead'
red              = '#bf616a'
tabs             = '#3b4252'
tabs-active      = '#465780'
white            = '#e5e9f0'
yellow           = '#ebcb8b'
dim-black        = '#353a45'
dim-blue         = '#668aab'
dim-cyan         = '#69a7ba'
dim-foreground   = '#abb1bb'
dim-green        = '#8aa872'
dim-magenta      = '#9d7495'
dim-red          = '#a54e56'
dim-white        = '#bbc3d4'
dim-yellow       = '#d9b263'
light-black      = '#465780'
light-blue       = '#8cafd2'
light-cyan       = '#93ccdc'
light-foreground = '#c7cdd9'
light-green      = '#b1d196'
light-magenta    = '#c895bf'
light-red        = '#d06f79'
light-white      = '#e7ecf4'
light-yellow     = '#f0d399'

