[colors]
background       = '#152528'
black            = '#2f3239'
blue             = '#5a93aa'
cursor           = '#e6eaea'
cyan             = '#a1cdd8'
foreground       = '#e6eaea'
green            = '#7aa4a1'
magenta          = '#ad5c7c'
red              = '#e85c51'
tabs             = '#2f3239'
tabs-active      = '#4e5157'
white            = '#ebebeb'
yellow           = '#fda47f'
dim-black        = '#282a30'
dim-blue         = '#4d7d90'
dim-cyan         = '#89aeb8'
dim-foreground   = '#cbd9d8'
dim-green        = '#688b89'
dim-magenta      = '#934e69'
dim-red          = '#c54e45'
dim-white        = '#c8c8c8'
dim-yellow       = '#d78b6c'
light-black      = '#4e5157'
light-blue       = '#73a3b7'
light-cyan       = '#afd4de'
light-foreground = '#eaeeee'
light-green      = '#8eb2af'
light-magenta    = '#b97490'
light-red        = '#eb746b'
light-white      = '#eeeeee'
light-yellow     = '#fdb292'

